//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautydemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_admin
    {
        [DisplayName("管理员编号")]
        public int aid { get; set; }
        [DisplayName("管理员姓名")]
        public string aname { get; set; }
        [DisplayName("管理员密码")]
        public string password { get; set; }
        [DisplayName("管理员确认密码")]
        public string confirmpassword { get; set; }
        [DisplayName("联系电话")]
        public string tel { get; set; }
    }
}
