//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautydemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_message
    {
        [DisplayName("留言编号")]
        public int mid { get; set; }
        [DisplayName("留言标题")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "标题不可为空")]
        public string title { get; set; }
        [DisplayName("留言内容")]
        public string mess { get; set; }
        [DisplayName("用户姓名")]
        public string name { get; set; }
        [DisplayName("留言时间")]
        public string messdate { get; set; }
    }
}
