//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautydemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_orderdetails
    {
        [DisplayName("详单编号")]
        public int id { get; set; }
        [DisplayName("用户姓名")]
        public string name { get; set; }
        [DisplayName("订单编号")]
        public Nullable<int> oid { get; set; }
        [DisplayName("商品编号")]
        public Nullable<int> pid { get; set; }
        [DisplayName("商品名称")]
        public string pname { get; set; }
        [DisplayName("商品单价")]
        public Nullable<decimal> price { get; set; }
        [DisplayName("购买数量")]
        public Nullable<int> nums { get; set; }
        [DisplayName("商品图片")]
        public string photo { get; set; }
        [DisplayName("商品状态")]
        public string state { get; set; }
    
        public virtual tb_orders tb_orders { get; set; }
        public virtual tb_product tb_product { get; set; }
    }
}
