//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautydemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_orders()
        {
            this.tb_orderdetails = new HashSet<tb_orderdetails>();
        }

        [DisplayName("订单编号")]
        public int oid { get; set; }
        [DisplayName("用户姓名")]
        public string name { get; set; }
        [DisplayName("下单时间")]
        public string orderTime { get; set; }
        [DisplayName("订单总价")]
        public Nullable<decimal> allPrice { get; set; }
        [DisplayName("联系电话")]
        public string tel { get; set; }
        [DisplayName("商品件数")]
        public Nullable<int> pcounts { get; set; }
        [DisplayName("收货地址")]
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_orderdetails> tb_orderdetails { get; set; }
    }
}
