//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautydemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_product()
        {
            this.tb_cart = new HashSet<tb_cart>();
            this.tb_orderdetails = new HashSet<tb_orderdetails>();
        }
        [DisplayName("商品编号")]
        public int pid { get; set; }
        [DisplayName("商品名称")]
        public string pname { get; set; }
        [DisplayName("商品图片")]
        public string photo { get; set; }
        [DisplayName("商品价格")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "价格不能为空")]
        [DataType(DataType.Currency, ErrorMessage = "价格格式输入错误")]
        public Nullable<decimal> price { get; set; }

        [DisplayName("商品库存")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "库存不能为空")]
        public Nullable<int> pnums { get; set; }
        [DisplayName("商品销量")]
        public Nullable<int> salenums { get; set; }
        [DisplayName("商品状态")]
        public string state { get; set; }
        [DisplayName("商品描述")]
        public string mess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cart> tb_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_orderdetails> tb_orderdetails { get; set; }
    }
}
