//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautydemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_user
    {
        [DisplayName("用户编号")]
        public int uid { get; set; }
        [DisplayName("用户姓名")]
        public string name { get; set; }
        [DisplayName("用户密码")]
        public string password { get; set; }
        [DisplayName("确认密码")]
        public string confirmpassword { get; set; }
        [DisplayName("用户地址")]
        public string address { get; set; }
        [DisplayName("用户电话")]
        public string tel { get; set; }
        [DisplayName("用户邮箱")]
        public string emil { get; set; }
    }
}
